import { Movie } from "types/interfaces";

export const movies: Movie[] = [
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: ["Crime", "Drama"],
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    rating: 9.2,
    duration: 175,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: ["Drama"],
    actors: ["Tim Robbins", "Morgan Freeman"],
    rating: 9.3,
    duration: 142,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    rating: 9.0,
    duration: 152,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "Pulp Fiction",
    director: "Quentin Tarantino",
    year: 1994,
    genre: ["Crime", "Drama"],
    actors: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"],
    rating: 8.9,
    duration: 154,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: ["Drama", "Romance"],
    actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    rating: 8.8,
    duration: 142,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "The Matrix",
    director: "The Wachowski Brothers",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    actors: ["Keanu Reeves", " Laurence Fishburne", "Carrie-Anne Moss"],
    rating: 8.7,
    duration: 136,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
  {
    title: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    genre: ["Crime", "Drama", "Thriller"],
    actors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    rating: 8.6,
    duration: 118,
    language: "English",
    subtitles: ["English", "Spanish", "French"],
    country: "USA",
  },
];
